test:
	g++ main.cpp game.cpp -O3 -I../vendor/stb_image/ -I../vendor/stb_truetype/ -I../vendor/ ../vendor/stb_image/stb_image.c ../vendor/glad/src/glad.c ../leif.c -I../ -o ../bin/game `pkg-config --cflags glfw3` -lglfw -I../vendor/glad/include/ -DLF_GLFW -DGLFW_INCLUDE_NONE -lm
